Pass along headers if present.
fedora-infra/fedmsg pull request #432
Opened 2017-06-22 16:40 UTC by ralphbean

These may be useful to filters or fedmsg.meta routines.

2017-06-23 13:29 UTC, jeremycline requested changes
There's a syntax error. I'd also really like to see test coverage for this change.

2017-06-23 13:29 UTC, jeremycline commented on fedmsg/consumers/ircbot.py
> +        if 'headers' in msg
You missed a colon here.

2017-06-26 13:10 UTC, ralphbean commented on fedmsg/consumers/ircbot.py
> +        if 'headers' in msg
Doh, thanks.  Rebased.

2017-06-26 13:57 UTC, ralphbean commented
> I'd also really like to see test coverage for this change.

Added in 951d1aa.

2017-06-27 17:00 UTC, jeremycline approved these changes
Looks good, thanks!

:shipit:

2017-06-27 17:00 UTC, merged