Return any return value from ._consume(..).
fedora-infra/fedmsg pull request #507
Opened 2018-03-09 21:09 UTC by ralphbean

In a non-zeromq case, it matters what the return value of _consume is.  (It is
a boolean, indicating if the message was successfully handled or not).  This,
in turn, gets used to figure out whether or not to send an ACK back to the
broker.

Here, the return values were being swallowed and turned into `None` values.

2018-03-09 21:10 UTC, mikebonnet commented
:+1:

2018-03-09 21:58 UTC, jeremycline requested changes
The change itself looks reasonable. Can you please write documentation for the function including its return value and tests?

Thanks.

2018-03-17 02:24 UTC, ralphbean commented
Docs and tests should be there, now.

2018-03-19 21:50 UTC, jeremycline approved these changes

2018-03-19 21:50 UTC, jeremycline commented
Thanks!

2018-03-19 21:50 UTC, merged

2018-03-19 22:54 UTC, ralphbean commented
Yay :)

@jeremycline, mind if I prepare a `fedmsg-1.1.1` release?

2018-03-20 16:48 UTC, jeremycline commented
Ah, sorry I missed this. For future reference I don't mind, but since I'm here I'll just write the release notes and tag a release.

2018-03-20 20:09 UTC, ralphbean commented
Hey, thanks!